version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    build: nginx
    depends_on:
      - host
    ports:
      - "80:80"

  host:
    container_name: host
    image: host
    build:
      context: packages/host
      dockerfile: Dockerfile.dev
      args:
        - SERVER_URI=${SERVER_URI}
    restart: always
    volumes:
      - /bin/.npmrc:/app/.npmrc
    ports:
      - "8000:8000"

  auth:
    container_name: auth
    image: auth
    build:
      context: packages/auth
      dockerfile: Dockerfile.dev
      args:
        - SERVER_URI=${SERVER_URI}
    restart: always
    ports:
      - "8082:8082"

  dashboard:
    container_name: dashboard
    image: dashboard
    build:
      context: packages/dashboard
      dockerfile: Dockerfile.dev
      args:
        - SERVER_URI=${SERVER_URI}
    restart: always
    ports:
      - "8083:8083"

  marketing:
    container_name: marketing
    image: marketing
    build:
      context: packages/marketing
      dockerfile: Dockerfile.dev
      args:
        - SERVER_URI=${SERVER_URI}
    restart: always
    ports:
      - "8081:8081"
