name: Docker Image CI

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: ["master"]

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v3
            
            - name: Install dependencies
              run: echo "code pushed"

            # - name: Build
            #   run: npx lerna run build