name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: start docker compose
        run: SERVER_URI=10.10.0.129 docker compose -f docker-compose.dev.yml up -d --build
