name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  example_matrix:
    strategy:
      matrix:
        containers: ["alarms", "dashboard", "ms-config"]
    runs-on: dev
    steps:
      - uses: actions/checkout@v3

      - name: Test cleanup
        run: docker system prune -f

      - name: print containers
        run: echo "${{ matrix.containers }} from the matrix strategy"
# jobs:
#   deploy:
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v3

#       - name: start docker compose
#         run: SERVER_URI=10.10.0.129 docker compose -f docker-compose.dev.yml up -d --build
