name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: start docker compose
        run: docker compose up --build

      # - name: Install dependencies
      #   run: npm i

      # - name: Start
      #   run: npm start
